version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - /app/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /app/redis/data:/data
    environment:
     - REDIS_REPLICATION_MODE=master
     - ALLOW_EMPTY_PASSWORD=yes
    network_mode: bridge