defaults: &defaults
  url: <%= ENV["REDIS_URL"] || "redis://localhost:6379/1" %>

development:
  <<: *defaults

test:
  <<: *defaults
  url: redis://localhost:6379/2

staging:
  <<: *defaults
  url:  <%= ENV['REDIS_URL'] %>

production:
  <<: *defaults
  url:  <%= ENV['REDIS_URL'] %>

